### ISSUE TITLE
[Bug] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1881: ordinal not in range(128)

### ISSUE THREAD

**Issue by franzramadhan** [traveloka/codebuild-terraform-ci-cd-image#54]
### Description

```
module_version: github.com/traveloka/terraform-aws-codebuild-terraform-ci-cd.git?ref=v0.3.2
image_version: 015110552125.dkr.ecr.ap-southeast-1.amazonaws.com/bei-codebuild-terraform-ci-cd-app:v0.2.6
```

### Known Issue

```
[Container] 2021/11/05 02:55:11 Running command ci-notify-plan-artifact-to-github-pr.py
--
195 | Traceback (most recent call last):
196 | File "/usr/local/bin/ci-notify-plan-artifact-to-github-pr.py", line 43, in <module>
197 | terraform_output=tf_plan
198 | File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1090, in render
199 | self.environment.handle_exception()
200 | File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 832, in handle_exception
201 | reraise(*rewrite_traceback_stack(source=source))
202 | File "/usr/local/bin/templates/terraform_output.j2", line 16, in top-level template code
203 | {{ terraform_output }}
204 | UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1881: ordinal not in range(128)
```

**Comment by franzramadhan** [comment]
Fixed by https://github.com/traveloka/codebuild-terraform-ci-cd-image/releases/tag/v0.3.0
